// Code generated by schema-generator. DO NOT EDIT.

package models

// CalculationResult: Calculation Result
type CalculationResult struct {
	Locale string  `json:"locale"`
	Op     string  `json:"op"`
	Result string  `json:"result"`
	Val1   float64 `json:"val1"`
	Val2   float64 `json:"val2"`
}

// CodeResponse: response to a CodeRequest
type CodeResponse struct {

	Id          int `json:"id"`
}

// Empty: (No description)
type Empty struct {
}

// Status: API status information
type Status struct {
	Branch    string `json:"branch"`
	Commit    string `json:"commit"`
	Platform  string `json:"platform"`
	Release   string `json:"release"`
	Timestamp string `json:"timestamp"`
}

type CodeRequest struct {

	AuthorisationId int `json:"authorisationId,omitempty"`
	VendorId int `json:"vendorId,omitempty"`
	CardId int `json:"cardId,omitempty"`
	Amount int `json:"amount"`
	Description string `json:"description,omitempty"`
}